# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:               # defines the scalar arguments once and apply them to any service defined/created in this file

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name


  App\:
    resource: '../src/App'
    exclude:
      - '../src/App/DependencyInjection/'
      - '../src/App/Domain/{Entity}'
      - '../src/App/Kernel.php'

  User\:
    resource: '../src/User'
    exclude:
      - '../src/User/Domain/{Entity}'

  Common\:
    resource: '../src/Common'
    exclude:
      - '../src/Common/Domain/{Entity}'

  _instanceof:
    Common\Domain\Bus\Command\CommandHandler:
      tags:
        - { name: messenger.message_handler, bus: command.bus }

    Common\Domain\Bus\Query\QueryHandler:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

  App\Application\EventListener\ExceptionSubscriber:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Application\EventListener\ContentBodyListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 1 }
